# Generated by Django 4.0.3 on 2022-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_total_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='delivery_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
