# Generated by Django 4.0.2 on 2022-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buy_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
