# Generated by Django 4.0.2 on 2022-05-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_buy_items_buy_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('shipping_partner', models.CharField(max_length=255)),
                ('product_location', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_partner',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.AddField(
            model_name='manageorder',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.order'),
        ),
    ]
