# Generated by Django 4.0.2 on 2022-05-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_manageorder_remove_order_buy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageorder',
            name='buy',
        ),
        migrations.AddField(
            model_name='manageorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
            preserve_default=False,
        ),
    ]
