# Generated by Django 4.0.2 on 2022-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_manageorder_buy_manageorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_status',
        ),
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
