# Generated by Django 4.0.2 on 2022-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_total_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
