# Generated by Django 4.0.2 on 2022-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_companyorder_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emp_id',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='emp_name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('Personal Use', 'Personal Use'), ('Company Use', 'Company Use')], default='Personal Use', max_length=20),
        ),
        migrations.DeleteModel(
            name='CompanyOrder',
        ),
    ]
